ALTER TABLE IF EXISTS GROUP_USERS DROP CONSTRAINT IF EXISTS FK1tqlbnvol79qrsa1i4rmjfsi6;
ALTER TABLE IF EXISTS GROUP_USERS DROP CONSTRAINT IF EXISTS FKjl8c6xgw3f899nw847rbg90sx;

DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS GROUPS CASCADE;
DROP TABLE IF EXISTS GROUP_USERS CASCADE;

CREATE TABLE USERS (
    chat_id BIGINT NOT NULL,
    metadata VARCHAR(255),
    user_state VARCHAR(255) CHECK (user_state IN ('IDLE','WAIT_FOR_GROUP_NAME','WAIT_FOR_NEW_GROUP_NAME','WAIT_FOR_GROUP_TOKEN')),
    PRIMARY KEY (chat_id)
);

CREATE TABLE GROUPS (
    id BIGSERIAL NOT NULL,
    drive_folder_id VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    vector_store_id VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE GROUP_USERS (
    group_id BIGINT,
    user_chat_id BIGINT NOT NULL,
    metadata VARCHAR(255),
    thread_id VARCHAR(255) NOT NULL UNIQUE,
    user_role VARCHAR(255) NOT NULL CHECK (user_role IN ('ADMIN','USER')),
    PRIMARY KEY (user_chat_id)
);

ALTER TABLE IF EXISTS GROUP_USERS ADD CONSTRAINT FK1tqlbnvol79qrsa1i4rmjfsi6 FOREIGN KEY (group_id) REFERENCES GROUPS;
ALTER TABLE IF EXISTS GROUP_USERS ADD CONSTRAINT FKjl8c6xgw3f899nw847rbg90sx FOREIGN KEY (user_chat_id) REFERENCES USERS;